### ISSUE TITLE
some improvements AHKT

### ISSUE THREAD

**Issue by wlastas** [zaafar/GameOverlay#216]
1. bug when entering the name of a new rule in a language other than English
![image](https://user-images.githubusercontent.com/5182065/167966057-cf7f5dfd-b649-4cf0-a578-4a041f68eb72.png)
must be:
![image](https://user-images.githubusercontent.com/5182065/167969228-cf38fa69-790c-4a8c-a37f-6f1ca4c913a1.png)

**Comment by wlastas** [comment]
![image](https://user-images.githubusercontent.com/5182065/167968559-2fae15a2-bf0f-4a17-ac82-43cc3cce241e.png)
cant add a label here now - it no longer maintained, because ( it's not private?) I'm confused

**Comment by zaafar** [comment]
@wlastas  change language from CORE settings.

**Comment by zaafar** [comment]
@wlastas did you change fonts settings from Core?

**Comment by wlastas** [comment]
Everything is ok now - I did not know about this setting.
I asked this before I saw your answer on the forum.
![image](https://user-images.githubusercontent.com/5182065/168296066-c032fd0c-309f-4fc2-a380-d5caf5e008ed.png)
