### ISSUE TITLE
feature request: Expedition/Excavated Chest Icons

### ISSUE THREAD

**Issue by LostPoE** [zaafar/GameOverlay#227]
"Metadata/Chests/LeaguesExpedition/" should add the Excavated Chest. Thank you!

**Comment by zaafar** [comment]
Can you do a screenshot of what they are currently shown as?

**Comment by LostPoE** [comment]
![image](https://user-images.githubusercontent.com/3904973/176442781-eaa1af75-b4f0-4543-8d5c-e985ba0d506c.png)
Looking to get these Chests added to the map.
