### ISSUE TITLE
feature request: get remaining buff duration for dynamic conditions

### ISSUE THREAD

**Issue by davidblanco996** [zaafar/GameOverlay#233]
Not sure if something like this is already possible but I did not manage to find out how.
This could be used for the new trickster ascendancy "heartstopper" to use a guard skill right before the "40% less dmg taken from hits" ends. As far as I know, the only option at the moment would be to use a dynamic condition to activate a guard skill if buff "40% less dmg over time taken" is active. However, if done this way there is a short time between losing "less dmg taken from hits" and the guard skill activating (mostly latency).
With this change one could activate a guard skill at the very end of "less dmg taken from hits" (<0,2s buff duration left) to be protected to whole time (assuming the right amount of increased skill effect duration and cooldown recovery).

I already tested it. Works for the current trickster heartstopper : "Buffs.HasTimeLeft("trickster_no_dot_taken") < 0,2"
BuffDictionary.cs:

```csharp
/// <summary>
///     Returns time left on buff
/// </summary>
/// <param name="id">The buff id</param>
public double HasTimeLeft(string id)
{
    if(this.source.TryGetValue(id, out var value))
    {
        return value.TimeLeft;
    }
    return 0;
}
```

IBuffDictionary.cs:

```csharp
/// <summary>
///     Returns time left on buff
/// </summary>
double HasTimeLeft(string id);
```

**Comment by zaafar** [comment]
can't say that it will be ready at league start time but the idea is good.

**Comment by zaafar** [comment]
try the following.

Buffs["rage"].charges < 25

or

Buffs["rage"].TimeLeft < 1

**Comment by davidblanco996** [comment]
thank you, just what I needed :D

just in case someone else is looking here searching for this feature too, there is a small part missing from the above to make it work ingame: Buffs["trickster_no_dot_taken"].timeLeft < 0.2

**Comment by zaafar** [comment]
also: Buffs["trickster_no_dot_taken"].PercentTimeLeft < 5
