### ISSUE TITLE
AHK Plugin - Should Run in Hidout bug

### ISSUE THREAD

**Issue by danthespal** [zaafar/GameOverlay#241]
Even if this is disable the plugin still activate the flasks and all I have setup in it

**Comment by zaafar** [comment]
in the AHK setting there is an option to disable in HO. select that option plz.

**Comment by danthespal** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/55256796/185900417-15f5a5d9-fde9-45ad-bbd5-4630f3887951.png">

I don;t know but there is only this

**Comment by zaafar** [comment]
Okay, I’ll look into this one.

**Comment by zaafar** [comment]
yeah, that's the development experience i.e. manually delete the config. Not sure how can I improve that.

**Comment by danthespal** [comment]
then is solved, thank you
